import { entityConfigs, singletonConfigs } from "./persistenceService";

export const sqliteTables = [
  "agents",
  "skills",
  "quests",
  "business_ideas",
  "validation_reports",
  "experiments",
  "experiment_decisions",
  "market_intelligence_reports",
  "research_source_captures",
  "seo_keyword_clusters",
  "demand_proof_reports",
  "experiment_analyses",
  "production_assets",
  "production_packs",
  "site_projects",
  "content_items",
  "publishing_diffs",
  "publishing_connectors",
  "spend_entries",
  "revenue_records",
  "portfolio_scores",
  "affiliate_offers",
  "offer_claim_reviews",
  "analytics_connectors",
  "search_console_properties",
  "search_console_metrics",
  "analytics_snapshots",
  "learning_cards",
  "job_schedules",
  "job_runs",
  "mission_drafts",
  "mission_runs",
  "mission_agent_steps",
  "mission_brief_sections",
  "mission_approval_batches",
  "agent_turn_results",
  "mission_tasks",
  "mission_artifacts",
  "command_ledger_entries",
  "approval_requests",
  "batch_approval_packages",
  "batch_approval_items",
  "approval_decision_records",
  "allowlist_entries",
  "activity_logs",
  "decision_logs",
  "improvement_proposals",
  "obsidian_notes",
  "settings",
  "budgets",
  "metrics",
  "tasks",
  "agent_orchestration_runs",
  "agent_artifacts",
  "agent_run_reviews",
  "agent_messages",
  "agent_performance_memories",
  "skill_gap_requests",
  "teamleader_chat_messages",
  "openclaw_commands",
  "openclaw_events",
  "openclaw_capabilities",
  "openclaw_permissions",
  "openclaw_runtime_status",
  "real_pilot_runs",
] as const;

export const sqliteSchemaPlan = sqliteTables.map((tableName) => ({
  tableName,
  phase: "Local E2E",
  status: entityConfigs.some((config) => config.tableName === tableName) || singletonConfigs.some((config) => config.tableName === tableName)
    ? "repository-backed"
    : "reserved",
  note: "SQLite tables use JSON payload columns plus practical status/type/stage/risk indexes.",
}));

export const sqliteService = {
  async getSchemaPlan() {
    return sqliteSchemaPlan;
  },
  async getPersistenceStatus() {
    return {
      enabled: true,
      adapter: "auto",
      note: "Tauri desktop uses SQLite through @tauri-apps/plugin-sql; browser development falls back to localStorage.",
    };
  },
};
